# Generated by Django 4.2.7 on 2023-12-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAnalysisApp', '0006_remove_subsection_unique_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('contact', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
        )
    ]
